BLINKIISPORTRAITS.media = {
	portraits = {
		blizz = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\blizz.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\blizz_mask_a.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\blizz_extra_a.tga",
			mask_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\blizz_mask_b.tga",
			extra_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\blizz_extra_b.tga",
		},
		blizz_up = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\blizz_up.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\blizz_up_mask_a.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\blizz_up_extra_a.tga",
			mask_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\blizz_up_mask_b.tga",
			extra_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\blizz_up_extra_b.tga",
		},
		circle = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\circle.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\circle_mask.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\circle_extra.tga",
		},
		diagonal = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\diagonal.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\diagonal_mask_a.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\diagonal_extra_a.tga",
			mask_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\diagonal_mask_b.tga",
			extra_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\diagonal_extra_b.tga",
		},
		diamond = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\diamond.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\diamond_mask.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\diamond_extra.tga",
		},
		drop = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_mask_a.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_extra_a.tga",
			mask_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_mask_b.tga",
			extra_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_extra_b.tga",
		},
		drop_mirror = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_mirror.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_mask_b.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_extra_b.tga",
			mask_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_mask_a.tga",
			extra_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_extra_a.tga",
		},
		drop_side = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_side.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_side_mask_a.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_side_extra_a.tga",
			mask_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_side_mask_b.tga",
			extra_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_side_extra_b.tga",
		},
		drop_side_mirror = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_side_mirror.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_side_mask_b.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_side_extra_b.tga",
			mask_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_side_mask_a.tga",
			extra_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\drop_side_extra_a.tga",
		},
		egg = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\egg.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\egg_mask.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\egg_extra.tga",
		},
		hexa = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\hexa.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\hexa_mask.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\hexa_extra.tga",
		},
		pad = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\pad.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\pad_mask.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\pad_extra.tga",
		},
		page = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\page.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\page_mask_a.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\page_extra_a.tga",
			mask_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\page_mask_b.tga",
			extra_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\page_extra_b.tga",
		},
		page_mirror = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\page_mirror.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\page_mask_b.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\page_extra_b.tga",
			mask_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\page_mask_a.tga",
			extra_mirror = "Interface\\Addons\\Blinkiis_Portraits\\media\\page_extra_a.tga",
		},
		square = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\square.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\square_mask.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\square_extra.tga",
		},
		square_round = {
			texture = "Interface\\Addons\\Blinkiis_Portraits\\media\\square_round.tga",
			mask = "Interface\\Addons\\Blinkiis_Portraits\\media\\square_round_mask.tga",
			extra = "Interface\\Addons\\Blinkiis_Portraits\\media\\square_round_extra.tga",
		},
	},
    extra = {
        extra_a = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_a.tga",
        extra_b = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_b.tga",
        extra_c = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_c.tga",
		extra_d = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_d.tga",
		extra_e = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_e.tga",
		extra_f = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_f.tga",
		extra_g = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_g.tga",
		extra_h = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_h.tga",
		extra_i = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_i.tga",
		extra_j = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_j.tga",
		extra_k = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_k.tga",
		extra_l = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_l.tga",
		extra_m = "Interface\\Addons\\Blinkiis_Portraits\\media\\extra_m.tga",

    }
}
